### ISSUE TITLE
All links to repositories and api are dead in the main readme

### ISSUE THREAD

**Issue by Jdban** [googleads/googleads-dfa-samples#1]
https://github.com/googleads/googleads-dfa-samples/blob/master/README.md

**Comment by jimper** [comment]
Hi there,

Sorry for the confusion, this repo is actually no longer supported. The API these samples were written for was shutdown some time ago. If you're working with our newer DCM/DFA Reporting and Trafficking API, please see our other repo @ https://github.com/googleads/googleads-dfa-reporting-samples.

Regards,
-- Jonathon Imperiosi, DCM API Team
